### ISSUE TITLE
EDUJAVA-1: environment setup

### ISSUE THREAD

**Issue by Qwerl** [i-oneEliseev/study_with_askar#1]
Установить всё что нужно в разработке
- JDK (https://www.oracle.com/technetwork/java/javase/downloads)
- Maven (https://maven.apache.org/download.cgi)
- IDE (https://www.jetbrains.com/idea/)

для упрощения из под винды советую использовать https://chocolatey.org/
он сам переменные окружения пропишет при установке

### **AC:** 
в терминале после ввода команд
1. выводятся пути
```
echo %JAVA_HOME%
echo %M2_HOME%
```
2. выводятся установленные версии
```
java -version
mvn -version
```

**Comment by i-oneEliseev** [comment]
![image](https://user-images.githubusercontent.com/25436609/70869521-e5dc4a00-1f9c-11ea-829c-b44fb3684c4b.png)
Done
